# -*- coding: utf-8 -*-
"""
dict_comparison_preview.py: Interactive Streamlit preview comparing Before (Prior theoretical OnomaDict)
versus After (Empirical acoustic feature extraction) across 4,122 Japanese & Korean onomatopoeia.
Features radar chart overlays, global distribution shifts, top delta discrepancy rankings, and audio playback.
"""

import sys
from pathlib import Path
from typing import Dict, Any, List

# Ensure analyzer src is in sys.path
SRC_DIR = Path(__file__).resolve().parent
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

try:
    import streamlit as st
except ImportError:
    print("[Error] Streamlit not installed. Run: pip install streamlit")
    st = None

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Configure fonts for Japanese and Korean support (prevent tofu characters)
plt.rcParams['font.family'] = ['Yu Gothic', 'Meiryo', 'Malgun Gothic', 'MS Gothic', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False

from acoustic_feature_extractor import AcousticFeatureExtractor


def init_page():
    if st is None:
        return
    st.set_page_config(
        page_title="OnomaDict Before/After Comparison Studio",
        page_icon="⚖️",
        layout="wide",
    )


def load_comparison_data():
    """Loads onomato_effort_comparison.csv generated by batch_dict_enricher."""
    project_root = Path(__file__).resolve().parent.parent.parent
    csv_path = project_root / "data" / "onomato_effort_comparison.csv"
    if not csv_path.exists():
        return None
    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    return df


def plot_radar_overlay(before_dict: dict, after_dict: dict, word: str, lang: str):
    """Plots superimposed radar chart comparing Before (blue dashed) vs After (red solid)."""
    labels = ["Weight (x1)", "Time (x2)", "Space (x3)", "Flow (x4)"]
    v_before = [
        before_dict.get("weight", 0.0),
        before_dict.get("time", 0.0),
        before_dict.get("space", 0.0),
        before_dict.get("flow", 0.0),
    ]
    v_after = [
        after_dict.get("weight", 0.0),
        after_dict.get("time", 0.0),
        after_dict.get("space", 0.0),
        after_dict.get("flow", 0.0),
    ]

    angles = np.linspace(0, 2 * np.pi, len(labels), endpoint=False).tolist()
    v_before += v_before[:1]
    v_after += v_after[:1]
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(4.5, 4.5), subplot_kw=dict(polar=True))

    # Before (Blue dashed)
    ax.plot(angles, v_before, color="#1f77b4", linewidth=2.0, linestyle="--", label="反映前 (Before: 理論値)")
    ax.fill(angles, v_before, color="#1f77b4", alpha=0.15)

    # After (Red solid)
    ax.plot(angles, v_after, color="#d62728", linewidth=2.5, linestyle="-", label="反映後 (After: 音声実測)")
    ax.fill(angles, v_after, color="#d62728", alpha=0.25)

    ax.set_ylim(0, 9)
    ax.set_yticks([2, 4, 6, 8])
    ax.set_yticklabels(["2", "4", "6", "8"], fontsize=8)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(labels, fontsize=10, fontweight="bold")
    ax.set_title(f"【{word}】 Effort 比較 ({lang})", y=1.08, fontsize=12, fontweight="bold")
    ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.1), fontsize=8.5)
    fig.tight_layout()
    return fig


def plot_waveform_f0(wav_path: Path):
    """Plots waveform and F0 pitch curve for the selected onomatopoeia."""
    extractor = AcousticFeatureExtractor()
    bundle = extractor.extract_features(str(wav_path))

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7, 3.2), sharex=True)
    times = bundle.time_frames

    # Waveform / RMS
    ax1.plot(times, bundle.rms_envelope, color="#1f77b4", linewidth=1.5, label="RMS Envelope")
    ax1.set_ylabel("RMS", fontsize=8)
    ax1.grid(True, linestyle="--", alpha=0.4)
    ax1.legend(loc="upper right", fontsize=8)
    ax1.set_title(f"音声波形 & F0ピッチ (持続: {bundle.duration_sec:.2f}s, アタック: {bundle.attack_time_ms:.1f}ms)", fontsize=9, fontweight="bold")

    # F0
    v_mask = bundle.f0_contour > 0
    if np.any(v_mask):
        ax2.plot(times[v_mask], bundle.f0_contour[v_mask], "o-", color="#2ca02c", markersize=2.5, label="F0 (Hz)")
        ax2.set_ylabel("Pitch (Hz)", fontsize=8)
        ax2.set_ylim(max(40, bundle.f0_min_hz - 20), bundle.f0_max_hz + 30)
    else:
        ax2.text(0.5, 0.5, "Unvoiced (無声)", ha="center", va="center", transform=ax2.transAxes)
    ax2.set_xlabel("Time (s)", fontsize=8)
    ax2.grid(True, linestyle="--", alpha=0.4)
    ax2.legend(loc="upper right", fontsize=8)

    fig.tight_layout()
    return fig


def main():
    if st is None:
        print("Please install streamlit and run: streamlit run dict_comparison_preview.py")
        return

    init_page()
    st.title("⚖️ OnomaDict Before vs After 比較プレビュー")
    st.caption("音声解析（実測値）を反映した新旧 OnomaDict の差異・シフト・レーダーチャート分析ダッシュボード")

    df = load_comparison_data()
    project_root = Path(__file__).resolve().parent.parent.parent
    audio_dir = project_root / "onomato-audio-recorder" / "dataset_output" / "audio_files"

    if df is None or len(df) == 0:
        st.warning("⚠️ 比較データが見つかりません。まずバッチ解析（batch_dict_enricher.py）を実行してください。")
        if st.button("🚀 バッチ解析を実行してデータを生成する"):
            with st.spinner("4,130件のオノマトペ音声を一括解析中..."):
                from batch_dict_enricher import enrich_dictionary
                stats = enrich_dictionary()
                st.success(f"解析完了！ {stats['enriched_entries']} 件のデータを生成しました。")
                st.rerun()
        return

    # Navigation Tabs
    tab1, tab2, tab3, tab4 = st.tabs([
        "🔍 単語個別比較 (レーダーチャート & 音声)",
        "📊 全体シフト・統計分析 (Global Shift)",
        "⚡ 差分ランキング Top 15 (Deltas)",
        "📋 全件データテーブル & CSV出力",
    ])

    # Tab 1: Single Word Detailed Comparison
    with tab1:
        st.subheader("🔍 単語ごとの Before / After 比較")
        c_filter1, c_filter2 = st.columns([1, 2.5])

        with c_filter1:
            sel_lang = st.selectbox("言語選択", ["JP (日本語: 2,061語)", "KR (韓国語: 2,061語)"], index=0)
            lang_code = sel_lang.split()[0]
            df_filtered = df[df["language"] == lang_code].copy()

            # Word selection list
            word_labels = [
                f"{row['word']}  —  {str(row.get('meaning_en', ''))[:35]}"
                for _, row in df_filtered.iterrows()
            ]
            chosen_idx = st.selectbox(
                f"オノマトペ単語を選択 ({len(df_filtered):,} 語)",
                range(len(df_filtered)),
                format_func=lambda i: word_labels[i],
                index=0,
            )
            item = df_filtered.iloc[chosen_idx]

        with c_filter2:
            st.markdown(f"### **【{item['word']}】** ({item['language']})")
            st.write(f"**意味**: {item.get('meaning_en', 'N/A')}")

            col_radar, col_metrics = st.columns([1.2, 1.2])

            with col_radar:
                before_eff = {
                    "weight": item["before_weight"],
                    "time": item["before_time"],
                    "space": item["before_space"],
                    "flow": item["before_flow"],
                }
                after_eff = {
                    "weight": item["after_weight"],
                    "time": item["after_time"],
                    "space": item["after_space"],
                    "flow": item["after_flow"],
                }
                fig_radar = plot_radar_overlay(before_eff, after_eff, item["word"], item["language"])
                st.pyplot(fig_radar)

            with col_metrics:
                st.markdown("#### 📐 Effort 4軸の数値差分 (After - Before)")
                m1, m2 = st.columns(2)
                m1.metric(
                    "Weight (重さ)",
                    f"{item['after_weight']:.2f}",
                    delta=f"{item['delta_weight']:+.2f}",
                )
                m2.metric(
                    "Time (急速さ)",
                    f"{item['after_time']:.2f}",
                    delta=f"{item['delta_time']:+.2f}",
                )

                m3, m4 = st.columns(2)
                m3.metric(
                    "Space (直接性)",
                    f"{item['after_space']:.2f}",
                    delta=f"{item['delta_space']:+.2f}",
                )
                m4.metric(
                    "Flow (拘束度)",
                    f"{item['after_flow']:.2f}",
                    delta=f"{item['delta_flow']:+.2f}",
                )

                st.write(f"**類似度 (Cosine Sim)**: `{item['cosine_similarity']:.3f}`  |  **ユークリッド距離**: `{item['euclidean_dist']:.2f}`")

            # 3-Way Auditory Comparison Studio (Before Synth vs After Synth vs Actual WAV)
            st.write("---")
            st.markdown("#### 🎧 3系統 A/B/C 聴き比べスタジオ (流体音響物理シンセサイザー vs 実際の音声)")
            st.caption("口腔内気圧ダイナミクス・声門連成・声道フォルマントから物理合成した音（古 vs 新）と、実際の録音音声を耳で聴き比べできます。")

            from onoma_synth_engine import OnomaSynthEngine
            synth = OnomaSynthEngine()

            # Render Before Synth WAV
            wav_bytes_before = synth.render_wav_bytes(before_eff, word=str(item["word"]))
            _, p_before = synth.synthesize_vector(before_eff, word=str(item["word"]))

            # Render After Synth WAV
            wav_bytes_after = synth.render_wav_bytes(after_eff, word=str(item["word"]))
            _, p_after = synth.synthesize_vector(after_eff, word=str(item["word"]))

            c_aud1, c_aud2, c_aud3 = st.columns(3)

            with c_aud1:
                st.markdown("##### 🟦 ① 古いシンセ音 (Before)")
                st.caption("事前の「理論値ベクトル」から物理合成")
                st.audio(wav_bytes_before, format="audio/wav")
                type_badge = "💥 破裂音" if p_before.get("is_plosive") else ("💨 摩擦音" if p_before.get("is_fricative") else "🗣️ 母音/共鳴音")
                st.info(
                    f"**分類**: `{type_badge}`\n\n"
                    f"**口腔内気圧**: `{p_before.get('max_p_oral_pa', 0)} Pa`\n\n"
                    f"**バースト強度**: `{p_before.get('burst_rms', 0):.3f}`\n\n"
                    f"**フォルマント**: F1=`{p_before.get('formant_f1_mean', 0)}Hz` / F2=`{p_before.get('formant_f2_mean', 0)}Hz`\n\n"
                    f"**アタック**: `{p_before.get('attack_ms', '-')} ms` | **F0**: `{p_before.get('base_f0_hz', '-')} Hz`"
                )

            with c_aud2:
                st.markdown("##### 🟥 ② 新しいシンセ音 (After)")
                st.caption("音声実測から得た「新ベクトル」から物理合成")
                st.audio(wav_bytes_after, format="audio/wav")
                type_badge_a = "💥 破裂音" if p_after.get("is_plosive") else ("💨 摩擦音" if p_after.get("is_fricative") else "🗣️ 母音/共鳴音")
                st.success(
                    f"**分類**: `{type_badge_a}`\n\n"
                    f"**口腔内気圧**: `{p_after.get('max_p_oral_pa', 0)} Pa`\n\n"
                    f"**バースト強度**: `{p_after.get('burst_rms', 0):.3f}`\n\n"
                    f"**フォルマント**: F1=`{p_after.get('formant_f1_mean', 0)}Hz` / F2=`{p_after.get('formant_f2_mean', 0)}Hz`\n\n"
                    f"**アタック**: `{p_after.get('attack_ms', '-')} ms` | **F0**: `{p_after.get('base_f0_hz', '-')} Hz`"
                )

            with c_aud3:
                st.markdown("##### 🎙️ ③ 実際の録音音声 (Actual)")
                st.caption("実際にマイク/TTSで録音したリアル音声")
                wav_file = audio_dir / str(item["audio_file"])
                if wav_file.exists():
                    st.audio(str(wav_file))
                    st.warning(
                        f"**実測アタック**: `{item['attack_time_ms']:.1f} ms`\n\n"
                        f"**実測F0平均**: `{item['f0_mean_hz']:.1f} Hz`\n\n"
                        f"**実測衝撃Jerk**: `{item['max_energy_jerk']:.0f}`"
                    )
                else:
                    st.caption("※ 対応するWAVファイルが見つかりません。")

            # Waveform and Pitch analysis
            if wav_file.exists():
                st.write("")
                fig_wave = plot_waveform_f0(wav_file)
                st.pyplot(fig_wave)

    # Tab 2: Global Distribution Shift
    with tab2:
        st.subheader("📊 全体シフト・統計分析 (理論値 vs 音声実測値)")
        st.write("4,122件のオノマトペ全体で、音声実測を反映したことによって各Effort軸がどのように変化したかの統計サマリーです。")

        col_s1, col_s2, col_s3, col_s4 = st.columns(4)
        col_s1.metric("解析総単語数", f"{len(df):,} 語")
        col_s2.metric("平均コサイン類似度", f"{df['cosine_similarity'].mean():.3f}")
        col_s3.metric("日本語 (JP) 件数", f"{len(df[df['language']=='JP']):,} 語")
        col_s4.metric("韓国語 (KR) 件数", f"{len(df[df['language']=='KR']):,} 語")

        st.write("---")
        st.markdown("#### 4軸ごとの平均変化量 (Mean Shift: After - Before)")

        df_jp = df[df["language"] == "JP"]
        df_kr = df[df["language"] == "KR"]

        summary_data = {
            "Effort 軸": ["Weight (重さ)", "Time (急速さ)", "Space (直接性)", "Flow (拘束度)"],
            "日本語 反映前平均": [df_jp["before_weight"].mean(), df_jp["before_time"].mean(), df_jp["before_space"].mean(), df_jp["before_flow"].mean()],
            "日本語 音声実測平均": [df_jp["after_weight"].mean(), df_jp["after_time"].mean(), df_jp["after_space"].mean(), df_jp["after_flow"].mean()],
            "日本語 差分 (Delta)": [df_jp["delta_weight"].mean(), df_jp["delta_time"].mean(), df_jp["delta_space"].mean(), df_jp["delta_flow"].mean()],
            "韓国語 反映前平均": [df_kr["before_weight"].mean(), df_kr["before_time"].mean(), df_kr["before_space"].mean(), df_kr["before_flow"].mean()],
            "韓国語 音声実測平均": [df_kr["after_weight"].mean(), df_kr["after_time"].mean(), df_kr["after_space"].mean(), df_kr["after_flow"].mean()],
            "韓国語 差分 (Delta)": [df_kr["delta_weight"].mean(), df_kr["delta_time"].mean(), df_kr["delta_space"].mean(), df_kr["delta_flow"].mean()],
        }
        df_summary = pd.DataFrame(summary_data)
        st.dataframe(df_summary.style.format({
            "日本語 反映前平均": "{:.2f}",
            "日本語 音声実測平均": "{:.2f}",
            "日本語 差分 (Delta)": "{:+.2f}",
            "韓国語 反映前平均": "{:.2f}",
            "韓国語 音声実測平均": "{:.2f}",
            "韓国語 差分 (Delta)": "{:+.2f}",
        }))

        # Plot shift bar chart
        fig_bar, ax_bar = plt.subplots(figsize=(8, 3.5))
        axes_labels = ["Weight", "Time", "Space", "Flow"]
        x = np.arange(len(axes_labels))
        width = 0.35

        ax_bar.bar(x - width/2, [df_jp[f"delta_{a.lower()}"].mean() for a in axes_labels], width, label="日本語 (JP) Shift", color="#1f77b4")
        ax_bar.bar(x + width/2, [df_kr[f"delta_{a.lower()}"].mean() for a in axes_labels], width, label="韓国語 (KR) Shift", color="#ff7f0e")
        ax_bar.axhline(0, color="black", linewidth=0.8, linestyle="--")
        ax_bar.set_xticks(x)
        ax_bar.set_xticklabels(axes_labels, fontweight="bold")
        ax_bar.set_ylabel("平均変化量 (Delta)")
        ax_bar.set_title("Effort 4軸の平均変化傾向 (音声解析による補正量)", fontsize=11, fontweight="bold")
        ax_bar.legend()
        ax_bar.grid(True, linestyle="--", alpha=0.4)
        fig_bar.tight_layout()
        st.pyplot(fig_bar)

    # Tab 3: Top Delta Rankings
    with tab3:
        st.subheader("⚡ 差分ランキング Top 15 (理論値から最も変化した単語)")
        st.write("音声実測によって、事前の音韻理論値から最も大きく変化したオノマトペのランキングです。")

        rank_axis = st.selectbox(
            "ランキング基準",
            [
                "Time (アタック・急速さの差分が大きい語)",
                "Weight (重厚感・低音成分の差分が大きい語)",
                "Space (直線性・直接性の差分が大きい語)",
                "Flow (拘束・減衰の差分が大きい語)",
                "総合ユークリッド距離が大きい語 (最も変化した語)",
            ],
            index=0,
        )

        axis_key_map = {
            "Time": "delta_time",
            "Weight": "delta_weight",
            "Space": "delta_space",
            "Flow": "delta_flow",
            "総合": "euclidean_dist",
        }
        chosen_col = [v for k, v in axis_key_map.items() if k in rank_axis][0]

        top_df = df.copy()
        top_df["abs_diff"] = top_df[chosen_col].abs()
        top15 = top_df.sort_values(by="abs_diff", ascending=False).head(15)

        st.dataframe(top15[[
            "word", "language", "meaning_en", "before_weight", "after_weight",
            "before_time", "after_time", "before_space", "after_space",
            "before_flow", "after_flow", chosen_col, "audio_file"
        ]])

    # Tab 4: Full Table & Export
    with tab4:
        st.subheader("📋 全件データテーブル & CSVダウンロード")
        st.write(f"全 {len(df):,} 件の反映前後の比較データです。")
        st.dataframe(df)

        project_root = Path(__file__).resolve().parent.parent.parent
        csv_file_path = project_root / "data" / "onomato_effort_comparison.csv"
        if csv_file_path.exists():
            with open(csv_file_path, "rb") as f:
                st.download_button(
                    label="📥 全比較データ CSV をダウンロード",
                    data=f.read(),
                    file_name="onomato_effort_comparison.csv",
                    mime="text/csv",
                )


if __name__ == "__main__":
    main()
